name: OpenDock
options:
  bundleIdPrefix: com.jitselambrichts
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  defaultConfig: Debug
  groupSortPosition: top
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    SWIFT_VERSION: "5.9"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: NO
packages:
  OpenDock:
    path: ..
targets:
  OpenDock:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: OpenDock
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jitselambrichts.OpenDock
        PRODUCT_NAME: OpenDock
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: OpenDock
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Jitse Lambrichts"
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_STYLE: Manual
    dependencies:
      - package: OpenDock
        product: OpenDockCore
    scheme:
      testTargets: []
